baseURL: "https://data-engineering-interviews.org/"
languageCode: "en-us"
DefaultContentLanguage: "en"
title: "Data Engineering Interviews"

contentDir: ./../content
staticDir: ./../static
publishDir: ./../public

build:
  useResourceCacheWhen: fallback
  writeStats: true

theme: "ace-documentation"
pygmentsCodeFences: true
pygmentsStyle: "monokailight"

disableSearch: false

frontmatter:
  disableReadmoreNav: true

params:
  ordersectionsby: "weight"
  disableSearch: false
  disableReadmoreNav: true # set true to hide prev/next navigation, default is false
  highlightClientSide: false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
  menushortcutsnewtab: true # set true to open shortcuts links to a new tab/window

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
   - "HTML"
   - "RSS"
   - "JSON"

menu: 
  shortcuts:
    -
      name: "<i class='fab fa-github'></i>"
      url: "https://github.com/kislerdm/data-engineering-interviews"
      weight: 3
    -  
      name: "<i class='fab fa-slack'></i>"
      url: "https://join.slack.com/t/dataengineeri-dg22406/shared_invite/zt-eeydzktu-uJ2mc4a45OrtzDMqekiqDQ"
      weight: 3
    -  
      name: "<i class='fab fa-linkedin'></i>"
      url: "https://linkedin.com/in/dkisler"
      weight: 3